name: Java CI with Maven

on: 
  push:
   branches: [ master ]
jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
       java-version: 1.8
    - name: Build with Maven
      run: mvn package
    - name: Deploy to tomcat 
      run: curl -v -u  ${{ secrets.Tomcat_Username }}:${{ secrets.Tomcat_Password }} -T /home/runner/work/spring3_Jms21_githubactions/spring3_Jms21_githubactions/target/spring3-mvc-maven-xml-hello-world-1.3.war 'http://35.154.218.29:8081/manager/text/deploy?path=/github_action_spring&update=true'
    
